### ISSUE TITLE
Which Super Mario Bros environment used?

### ISSUE THREAD

**Issue by seungjaeryanlee** [openai/large-scale-curiosity#1]
I want to analyze how learned features and random features compare in transfer learning throughout Super Mario Bros environments. Are the environments the same as those in the `noreward-rl` repository?

**Comment by seungjaeryanlee** [comment]
Thank you for the response. I guess they built it from source then! (https://github.com/openai/retro/issues/61) Hope I have better luck this time.

**Comment by yburda** [comment]
Confirming that we used SuperMarioBros-Nes environment in gym retro.
