### ISSUE TITLE
Cannot run the run.py because mpi4py has no module "MPI"

### ISSUE THREAD

**Issue by Niels-ns** [openai/large-scale-curiosity#15]
(tf-nightly) C:\Users\Niels\Documents\GitHub\large-scale-curiosity>python run.py
    no OpenGL.GLU
    Traceback (most recent call last):
      File "run.py", line 15, in <module>
        from mpi4py import MPI
    ImportError: DLL load failed: The specified module could not be found.

I installed mpi4py through pip install. Any got any idea how to fix this?

**Comment by kevin5k** [comment]
@Niels-ns + @jachiam,
I have recently been having encountering this issue on Win10 via the anaconda environment and I could not find anyone else encountering this issue. Hence, I would like to share the solution here -->

The issue I encountered was that when I executed the ppo installtest command, I faced the same error message which you had reported. It appears that is more of a Windows 10 environment issue than the anaconda issue.

Solution
1) Download and install the Windows MPI SDK and exe from [microsoft](https://www.microsoft.com/en-us/download/details.aspx?id=56511). 
2) Upon completion, close all instances of Anaconda
3) Launch a new instance of Anaconda and activate your environment (eg. spinningup)
4) Execute "python -m spinup.run ppo --hid "[32,32]" --env LunarLander-v2 --exp_name installtest --gamma 0.999"

**Comment by Hsgngr** [comment]
> The issue I encountered was that when I executed the ppo installtest command, I faced the same error message which you had reported. It appears that is more of a Windows 10 environment issue than the anaconda issue.
> 
> Solution
This doesn't work.

**Comment by Hsgngr** [comment]
Currently the support of OpenAI for Windows is weak, everything works smoothly in WLS or directly ubuntu.
