### ISSUE TITLE
where is the source code?

### ISSUE THREAD

**Issue by AlisaBen** [openai/large-scale-curiosity#2]
only the README file, but no source code……

**Comment by simoninithomas** [comment]
Hi,
Unfortunately it's not released yet.

**Comment by AlisaBen** [comment]
Got it, thanks for your share.

**Comment by Narsil** [comment]
Any timeframe for the code release ?

**Comment by Cerebrock** [comment]
C'mon guys! :B

**Comment by rubenvillegas** [comment]
I wonder if people consider the authors may be working on other projects, and not just on the release of this specific code. Let them do it on their own time.

**Comment by simoninithomas** [comment]
Hi, I'm currently working on an implementation of Curiosity Driven I hope to publish it this week, hope it will helps http://bit.ly/2DcJrOp

**Comment by mimoralea** [comment]
@rubenvillegas the readme mentions the code will be released soon...

From the README.md:
"""
Installation and Usage
Stay tuned! To be released soon.
"""

**Comment by rubenvillegas** [comment]
@mimoralea Exactly...

**Comment by harri-edwards** [comment]
We released an initial version. We will make minor changes in the next couple days. Closing the issue for now.
