### ISSUE TITLE
Clarification in the forward loss computation

### ISSUE THREAD

**Issue by srama2512** [openai/large-scale-curiosity#3]
https://github.com/openai/large-scale-curiosity/blob/0c3d179fd61ee46233199d0891c40fbe7964d3aa/dynamics.py#L23
https://github.com/openai/large-scale-curiosity/blob/0c3d179fd61ee46233199d0891c40fbe7964d3aa/dynamics.py#L65

In the above lines, the features have been disconnected from the loss gradient. Does the forward loss not affect the feature representation?

**Comment by harri-edwards** [comment]
That's right, otherwise the loss would push the features all be close.

**Comment by harri-edwards** [comment]
Yes it can be made to work, but you have to tune the scale of the forward loss. In addition you can't use random features if you use the forward loss.

**Comment by zfar-** [comment]
Hi, 
I am having a similar problem and would like if @harri-edwards  you can comment on it. 

I am also working with the forward model for the intrinsic reward on attari (Pong , Breakout etc) but with the passage of time, the prediction error becomes very low as it has learned the semantics of the state spaces. But for an agent, the reward signal is not that explicit so the agent doesn't learn anything as the forward loss varies around 0 (e.g. 0.05 , 0.006) over the number of timesteps. 

to what extent we need to scale the reward in order for the agent to learn, considering lower and upper bound (-1 , 1)
