### ISSUE TITLE
AttributeError: 'RetroEnv' object has no attribute 'BUTTONS

### ISSUE THREAD

**Issue by jamesrichter** [openai/large-scale-curiosity#8]
I get this error

> 
> Traceback (most recent call last):
>   File "run.py", line 211, in <module>
>     start_experiment(**args.__dict__)
>   File "run.py", line 31, in start_experiment
>     envs_per_process=args['envs_per_process'])
>   File "run.py", line 45, in __init__
>     self._set_env_vars()
>   File "run.py", line 102, in _set_env_vars
>     env = self.make_env(0, add_monitor=False)
>   File "run.py", line 134, in make_env_all_params
>     env = make_mario_env()
>   File "/home/jim/Downloads/large-scale-curiosity-master/wrappers.py", line 249, in make_mario_env
>     buttons = env.BUTTONS
> AttributeError: 'RetroEnv' object has no attribute 'BUTTONS'

When I run
> python3 run.py --num_timesteps=1000000 --env_kind="mario"

**Comment by jamesrichter** [comment]
I changed "BUTTONS" to "buttons" in wrappers.py

**Comment by harshdeepkukreja** [comment]
"AttributeError: 'RetroEnv' object has no attribute 'em' " can anyone help with this?

**Comment by Syzygianinfern0** [comment]
> "AttributeError: 'RetroEnv' object has no attribute 'em' " can anyone help with this?

Removing `env.close()` everywhere fixed the error for me.

**Comment by Xman081101** [comment]
Removing env.close() everywhere fixed the error for me. 

thanks for Syzygianinfern
